<?php

//DON'T TOUCH
DEFINE('BASE_URL_API_PAYPAL', 'https://api-3t.sandbox.paypal.com/nvp?');
DEFINE('VERSION_API_PAYPAL', 124);


// UPDATE THE FOLLOWING LINES
DEFINE('USERNAME_FACILITATOR', '');
DEFINE('PASSWORD_FACILITATOR', '');
DEFINE('SIGNATURE_FACILITATOR', '');
