<?php
DEFINE('VERSION_API_PAYPAL', 124);
DEFINE('SITE_PATH', realpath(dirname(__FILE__)));


// UPDATE THE FOLLOWING LINES
DEFINE('USERNAME_FACILITATOR', 'younes.sadmi-facilitator_api1.gmail.com');
DEFINE('PASSWORD_FACILITATOR', 'Y8L9MQSJL7MEPJSJ');
DEFINE('SIGNATURE_FACILITATOR', 'AFcWxV21C7fd0v3bYYYRCpSSRl31Aqkx9PCclDaHbdmVkgfpneMdajEk');