<?php
DEFINE('VERSION_API_PAYPAL', 124);
DEFINE('SITE_PATH', realpath(dirname(__FILE__)));


// UPDATE THE FOLLOWING LINES
DEFINE('USERNAME_FACILITATOR', ');
DEFINE('PASSWORD_FACILITATOR', '');
DEFINE('SIGNATURE_FACILITATOR', '');
